name: NASA Project CI
on: # when the pipeline process will triger (push or pr on master)
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest # macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2 # built in github actions
      - name: Use Node.js version 16
        uses: actions/setup-node@v2 # we are in above bullet point
        with:
          node-version: "16"
      - run: npm install
      - run: npm run build -- prefix client

  # deploy:
  # needs: build # now build will run first, then deploy
